'use client'

import React, { useState } from 'react'
import { useAuth } from '@/components/providers/supabase-provider'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Users2, ArrowRight } from 'lucide-react'
import { toast } from 'sonner'

interface JoinGroupDialogProps {
  onSuccess: () => void
}

export function JoinGroupDialog({ onSuccess }: JoinGroupDialogProps) {
  const [open, setOpen] = useState(false)
  const [inviteCode, setInviteCode] = useState('')
  const [submitting, setSubmitting] = useState(false)
  const { supabase } = useAuth()

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!inviteCode.trim()) {
      toast.error('Invite join code is required')
      return
    }

    setSubmitting(true)
    try {
      // Call standard Postgres RPC join_group_by_code
      const { data: groupUuid, error } = await supabase.rpc('join_group_by_code', {
        code: inviteCode.trim().toUpperCase(),
      })

      if (error) throw error

      toast.success('Successfully joined the group workspace!')
      setInviteCode('')
      setOpen(false)
      onSuccess()
    } catch (error: any) {
      console.error('Error joining group:', error)
      toast.error(error.message || 'Failed to join group. Verify invite code.')
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger render={
        <Button variant="outline" className="border-neutral-900 bg-neutral-950/40 hover:bg-neutral-900 text-neutral-300 hover:text-white rounded-xl py-5 px-5 font-medium flex gap-2">
          <Users2 className="h-4 w-4 text-neutral-300" /> Enter Join Code
        </Button>
      } />
      <DialogContent className="border-neutral-900 bg-neutral-950/95 text-white max-w-[400px] rounded-2xl shadow-2xl backdrop-blur-xl">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2 text-xl font-bold bg-linear-to-b from-white to-neutral-400 bg-clip-text text-transparent">
            Join Family Group
          </DialogTitle>
          <DialogDescription className="text-slate-400 text-xs mt-1">
            Access a shared workspace by entering the code generated by the group creator.
          </DialogDescription>
        </DialogHeader>

        <form onSubmit={handleSubmit} className="space-y-4 mt-2">
          {/* Join Code Input */}
          <div className="space-y-2">
            <Label htmlFor="inviteCode" className="text-xs text-slate-300">Invite Code</Label>
            <Input
              id="inviteCode"
              placeholder="FAM-XXXXXX"
              value={inviteCode}
              onChange={(e) => setInviteCode(e.target.value.toUpperCase())}
              className="border-neutral-800 bg-neutral-900/50 rounded-xl text-slate-200 uppercase tracking-widest font-mono text-center text-lg placeholder-neutral-700 focus:outline-none focus:ring-1 focus:ring-white focus:border-white py-6"
            />
          </div>

          {/* Submit */}
          <Button
            type="submit"
            disabled={submitting}
            className="w-full bg-white hover:bg-neutral-200 text-black font-semibold rounded-xl py-6 shadow-2xl flex items-center justify-center gap-2 border border-transparent"
          >
            {submitting ? 'Verifying Invite...' : 'Join Group Space'}
            <ArrowRight className="h-4 w-4" />
          </Button>
        </form>
      </DialogContent>
    </Dialog>
  )
}
